### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by mpvdk** [neex/http2smugl#1]
Hello Emil! 

First of all, thank you for developing this tool. Unfortunately I have some issues that I can't seem to resolve. 

When I run "go run http2smugl.go request https://www.whatever.com "transfer-encoding : chunked"", I get the following output:

```
# command-line-arguments
./http2smugl.go:56:18: undefined: Header
./http2smugl.go:66:31: undefined: Header
./http2smugl.go:69:23: undefined: RequestParams
./http2smugl.go:99:11: undefined: detectMultipleTargets
./http2smugl.go:131:32: undefined: RequestParams
./http2smugl.go:132:24: undefined: DoRequest
```

I have go version 1.15.5 installed and downloaded both cobra and pflag directly from github with go get. 

I have looked at the code, but I am unfamiliar with golang and I can't seem to resolve it.

**Comment by mpvdk** [comment]
Tried to run with golang 1.14 - same results.

**Comment by neex** [comment]
Hello,

You should run it like this: `go run . request ...`. This will include all the files, not only one.

P.S. I'm very sorry that there's no readme. I will write it in a week or so. Didn't expect that someone will actually look into this)

**Comment by neex** [comment]
As the documentation has finally arrived, I'm closing this one.
