### ISSUE TITLE
How to interpret this tool output? (This is not an issue)

### ISSUE THREAD

**Issue by cocoh-23** [neex/http2smugl#10]
Hello, what would be the meaning of this output? Just that the backend server is parsing the Content-Length header, thus not meaning that it is or is not vulnerable? 

http_method=GET, detect_method=detect content length parsing, smuggling_method=no header smuggling, smuggling_variant=N/A, padding_method=no padding headers: distinguishable not by timing

Thank you very much.

**Comment by neex** [comment]
Hello,

This exact line look like false positive.

I think that reading the source code is the best way to understand the output right now)
