### ISSUE TITLE
Error compiling in GO

### ISSUE THREAD

**Issue by jmaravi** [neex/http2smugl#12]
Got the following message when running:
go get github.com/neex/http2smugl

go build github.com/lucas-clemente/quic-go/internal/qtls: build constraints exclude all Go files in /root/go/src/github.com/lucas-clemente/quic-go/internal/qtls

and no executable was created

**Comment by cberman** [comment]
What version of Go are you using? I was able to resolve the same error message by upgrading from
`go version go1.15.3 darwin/amd64`
to
`go version go1.17.1 darwin/amd64`.

**Comment by yehgdotnet** [comment]
```
git clone https://github.com/neex/http2smugl.git
cd http2smugl
go build .
```

**Comment by neex** [comment]
Hello,

You need to upgrade the Golang to the latest version.
