### ISSUE TITLE
Error: server dropped connection, error=error code PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Sarfu47** [neex/http2smugl#13]
Whenever, I request at of http2 smuggl on a any of domain showing this type of error - Error: server dropped connection, error=error code PROTOCOL_ERROR 
How we get what is vulnerable or not

**Comment by Lopseg** [comment]
Same here

**Comment by neex** [comment]
Hello,

The reason for this error is that the domain probably does not support HTTP/2 at all. Also, make sure you provide https link (not http one).
