### ISSUE TITLE
HTTPS only?

### ISSUE THREAD

**Issue by engn33r** [neex/http2smugl#14]
Currently, the http2smugl tool only allows the https schema. Is there a reason why HTTP2 smuggling cannot support unencrypted http? I tried to add the http schema in the http_client.go file, but I am receiving an error of `read: connection reset by peer` when I try to run against a http endpoint with my modified code. I will investigate this more to try to create a PR, but I wanted to check if I am missing other obvious changes needed beyond the http_client.go file.

**Comment by neex** [comment]
Hello,

The tool currently uses HTTP2 & HTTP3 specific methods of HTTP Request Smuggling. HTTP2 does not run over unencrypted connections in the real world as well as HTTP3 - thus https only.
