### ISSUE TITLE
Need support for HTTP/S and SOCKS5 proxy for HTTP/3

### ISSUE THREAD

**Issue by ArisBaget** [neex/http2smugl#17]
This is very cool but can you add support for HTTP/S and SOCKS5 proxy for HTTP/3, is it possible?

**Comment by neex** [comment]
Hello,

Unfortunately, it is not possible.

HTTP/3 connections use UDP for transport, and SOCKS/5 or HTTP proxies cannot proxy UDP (well, SOCKS5 technically can, but I've never seen it available at any real proxy server).
