### ISSUE TITLE
[bug] line 55 in smuggle.go format error

### ISSUE THREAD

**Issue by cyal1** [neex/http2smugl#3]
line 55 in smuggler.go 
`h.Value = fmt.Sprintf("val%s%s:%s%s%s", v.Newline, h.Name, h.Value[0], pad, h.Value[1:])` return 
`val\r\ncontent-length:%!s(uint8=45)00000000001`
fixed:
`h.Value = fmt.Sprintf("val%s%s:-%s%s", v.Newline, h.Name, pad, h.Value[1:])`

**Comment by neex** [comment]
Thank you very much!

FIxed in #4.
