### ISSUE TITLE
Error when installing from `go get`

### ISSUE THREAD

**Issue by zaidanr** [neex/http2smugl#5]
Error message: 
# github.com/neex/http2smugl
/root/go/pkg/mod/github.com/neex/http2smugl@v0.0.0-20210814084653-18a7a0fa63be/http3.go:63:66: undefined: quic.VersionDraft32

**Comment by uchihaluckycs** [comment]
same error

**Comment by neex** [comment]
Hey, could you please provide the output of `go version`?

**Comment by uchihaluckycs** [comment]
go version go1.17 linux/amd64
