### ISSUE TITLE
Every Time I Tried To Install http2smugl , I faced This Error

### ISSUE THREAD

**Issue by 0xAwali** [neex/http2smugl#7]
While Installing http2smugl , I Get This Error 

![Screenshot_2021-09-07_13_14_24](https://user-images.githubusercontent.com/54332136/132336476-9069ad79-3097-4dd5-b162-47d0687c673a.jpg)

**Comment by neex** [comment]
Hello,

What is the output of `go version`?

**Comment by 0xAwali** [comment]
### go version go1.15.15 linux/amd64

**Comment by trickster0** [comment]
I am having the same issue

**Comment by neex** [comment]
Hello,

go 1.15 is not supported by https://github.com/lucas-clemente/quic-go, which is a dependency for this project.

Please retry using latest go version. You can use a golang docker as well (something like `docker run --rm -it  -w $PWD -v $PWD:$PWD  golang:1.17 go build .` should make the `http2smugl` binary appear in the current directory).
